apiVersion: v1
kind: Service
metadata:
  name: tb-grpc-loadbalancer-external
  namespace: thingsboard
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: tb-node
  ports:
    - port: 7070
      targetPort: 7070
      name: edge
    - port: 9090
      targetPort: 9090
      name: grpc